### ISSUE TITLE
Difference b/w Structure and Station for Market Orders?

### ISSUE THREAD

**Issue by HerrNerdstrom** [burberius/eve-esi#100]
Hi,

I'm building an application that fetches market orders from both Jita and a Keepstar in nullsec. I have a few questions about how best to do this and to make comparisons between the orders returned:

1) The best method I have found to retrieve the orders from the Keepstar is to use the getMarketsStructuresStructureId() set of methods. Is this the best method to use?
2) The best method I have found to retrieve market orders from a station (like Jita 4-4) is to use the getMarketsRegionIdOrders() set of methods, since I can't find an equivalent method to #1 above for a station. This returns all orders in The Forge. Is there a better methodology that doesn't use as much server processing time and require an additional pruning step in the client application?
3) When comparing the responses from these two above, one is a MarketStructuresResponse and the second is the MarketOrderResponse. They seem to be functionally equivalent, but I'm having difficulty writing code that doesn't replicate methods (getting some Erasure error when trying to overload methods). Can these two response types be the same, or do you know how to programmatically compare them easily?

The library is working well for me, I'm just in the process of refactoring the code before I add some new features. Thanks!

**Comment by burberius** [comment]
Hi HerrNerdstrom

I don't know about 1. and 2. as I didn't use that part for some years now. But I guess your expectations are right.

About 3: Those responses are generated from the API definitions and CCP has a lot of redundancy in ESI, but that's a result of how ESI works. We have to live with that!

I wouldn't compare the two types directly but let that do a database:
- create an entity with a subset of the properties
- create a factory that can create the entity from both responses
- read the data, transform the objects and write the result in a (in memory) database
- after both are fetched, just fire the queries against the database.
That way you can also compare with old values...
