### ISSUE TITLE
JWT payload parsing fails if there were no scopes selected

### ISSUE THREAD

**Issue by kcbanner** [burberius/eve-esi#101]
There is an NPE if there is no `scp` key in the JWT, which can happen if you are using SSO simply to authorize and not request any scopes:

```
            JsonElement element = jsonObject.get("scp");
            if (element.isJsonArray()) {
```

**Comment by GoldenGnu** [comment]
Bug confirmed.
I will try to get a new release done as soon as possible.

**Comment by GoldenGnu** [comment]
3.4.0 have been released with a fix for this bug.

**Comment by kcbanner** [comment]
Thanks so much!
