### ISSUE TITLE
OAuth doesn't support a way to get/set codeVerifier string

### ISSUE THREAD

**Issue by kcbanner** [burberius/eve-esi#102]
The issue I'm having is that OAuth itself isn't serializeable, and therefore I can't stash it in my session store (the callback may be served on another app instance, so I can't just keep it in memory).

If there were a getter/setter for the codeVerifier, I could simply stash the string in my session and recreate an identical OAuth in the callback handler.

I can work on a PR for this if you'd like, or if there is a design issue I'm missing please let me know.

**Comment by GoldenGnu** [comment]
I have made a PR #103 with the changes and have asked the other devs to review it.

**Comment by GoldenGnu** [comment]
I won’t have time to do the release today and probably not tomorrow either. So, currently planning to do the release this weekend.

**Comment by GoldenGnu** [comment]
Released in 3.5.0
