### ISSUE TITLE
How can I get the characterID after auth success

### ISSUE THREAD

**Issue by TheColdVoid** [burberius/eve-esi#112]
Excuse me, I have a question. After the user is authorized to log in, when using the API, it needs to be based on the user's characterID, but I don't know how to use this library to query it.Looking forward to your answer, thank you

**Comment by GoldenGnu** [comment]
You have two options:
### Use the JSON Web Token (JWT):
_Does not require any additional requests_
```
ApiClient apiClient = new ApiClientBuilder().build()
OAuth auth = (OAuth) apiClient .getAuthentication("evesso");
JWT jwt = auth.getJWT();
if (jwt == null) {
    //Handle missing Auth
}
JWT.Payload payload = jwt.getPayload();
Integer characterID = payload.getCharacterID();
```


### Use SsoApi (wrapper for ESI Meta verify):
_Require an additional request_
```
SsoApi ssoApi = new SsoApi();
CharacterInfo characterInfo = ssoApi.getCharacterInfo();
Integer characterID = characterInfo.getCharacterID();
```

**Comment by TheColdVoid** [comment]
> You have two options:
> 
> ### Use the JSON Web Token (JWT):
> _Does not require any additional requests_
> 
> ```
> ApiClient apiClient = new ApiClientBuilder().build()
> OAuth auth = (OAuth) apiClient .getAuthentication("evesso");
> JWT jwt = auth.getJWT();
> if (jwt == null) {
>     //Handle missing Auth
> }
> JWT.Payload payload = jwt.getPayload();
> Integer characterID = payload.getCharacterID();
> ```
> 
> ### Use SsoApi (wrapper for ESI Meta verify):
> _Require an additional request_
> 
> ```
> ApiClient apiClient = new ApiClientBuilder().build()
> SsoApi ssoApi = new SsoApi(apiClient);
> CharacterInfo characterInfo = ssoApi.getCharacterInfo();
> Integer characterID = characterInfo.getCharacterID();
> ```

problem solved,thank you for your patience
