### ISSUE TITLE
Issue with getting new Auth key

### ISSUE THREAD

**Issue by seenkley** [burberius/eve-esi#115]
The official esi documentation states when it comes to updating the auth token via a refresh token:
The Authorization header must be the word "Basic" followed by the base-64 encoded string of {client id}:{client_secret}.

After digging a bit around in the code i saw, that the method net.troja.eve.esi.auth.OAuth#refreshToken does not include the client_secret.

I'm not sore if the missing secret causes the 400 response when calling the update method.

Am I missing something with the usage?

i'm using version 4.1.0
![image](https://user-images.githubusercontent.com/12306801/98440331-757c7100-20f8-11eb-8866-fcaa4ad34b05.png)

**Comment by GoldenGnu** [comment]
I see you closed the issue, however, I just want to explain why eve-esi does not use the secret:
eve-esi uses PKCE ([doc](https://github.com/esi/esi-docs/blob/master/docs/sso/native_sso_flow.md)) and that is why the secret is never used. The reason for using PKCE is that I use it in jEveAssets, that is a desktop application, that can not use the normal flow.

**Comment by seenkley** [comment]
Oh boy you are fast 👍 
Yea i just saw the comment above the method, that the secret is only required to prevent xrsf...
Sadly, I'm still not able to make it run. I always get a 400 in net.troja.eve.esi.auth.OAuth#update when con.getInputStream() is called. Any idea on that ?

**Comment by burberius** [comment]
Have a look into my code of pvetracker, perhaps you find a solution there: https://github.com/burberius/pvetracker/blob/master/src/main/java/net/troja/eve/pve/esi/LocationService.java

I store the refresh token for each logged in account and when accessing the API I set it before each call in the api client.

**Comment by GoldenGnu** [comment]
Here are some info that may be helpful:
1) Not setting a user-agent (see: https://github.com/burberius/eve-esi#version-300-changes). SSO can be very strict with this, it should `program name/version`
2) The ApiClient is thread safe, but, only support one refresh_token
3) You must set the client_id
4) Here is a example of how to get a refresh_token:
https://github.com/burberius/eve-esi/blob/master/src/test/java/net/troja/eve/esi/api/auth/SsoAuthTest.java#L182

**Comment by seenkley** [comment]
Thanks burberius, I'll look into it!
GoldenGnu - thanks as well.
Just to clarify, the client id is the id I get when registering the service on the eve.dev site - right ?

I really don't want to waste your time, but maybe you can take a look at https://github.com/seenkley/moon-goo-tax-backend/compare/testBranch?expand=1#diff-880829de4dd879b72211e81ce30a2230013463aee1e97b0f91b54f7ce38da86cR35
Thats how I currently initialize the ApiClient

I let someone login, save the credentials into a db and use them later on.

**Comment by GoldenGnu** [comment]
ATM you're creating new instances of ApiClient for each ClientCredentials (as you should), however, you only store the last entry?
You need to store each ApiClient. Something like:
```
Map<ClientCredentials, ApiClient> api  = new HasMap<>();
...
api.put(client, new ApiClientBuilder().clientID(client.getApplicationId()).refreshToken(client.getRefreshToken()).okHttpClient(getHttpClient()).build());
...
for (ApiClient client api.values()) {
   searchApi.setApiClient(api.get(client));
...
}
```

**Comment by burberius** [comment]
Yes, the client ID is the one you get when you create your application on the eve dev site.

https://github.com/seenkley/moon-goo-tax-backend/compare/testBranch?expand=1#diff-726877b5786115da50987beafd74159e4e44bcfc7f083ee3e7d8a76bb26f2715R38

You store the authentication code used in the initial login process, but not the refresh token! This code is just valid for this single login!

It looks like you allow several clients to login, so you always have to set the refresh token of the client, before doing an authenticated api operation.

**Comment by burberius** [comment]
For more questions, you can join our discord: https://discord.gg/SH6jz74s

**Comment by seenkley** [comment]
Ok, it worked now!
As you said, I stored the wrong token instead of the refresh token... Thank you very much guys!
I joined you discord, so expect more questions in the future 👍
