### ISSUE TITLE
Getting an internal server error when calling POST /characters/{character_id}/assets/names/

### ISSUE THREAD

**Issue by JoshuaKeno65** [burberius/eve-esi#128]
I am trying to read a character´s assets and add the names of the found location ids. 
Reading the assets works fine. But when I feed the location ids into postCharactersCharacterIdAssetsNames I always get an internal server error (http 500). 

Here is the code snippet that calls the method throwing the exception: 

```
       List<CharacterAssetsNamesResponse> response = new ArrayList<CharacterAssetsNamesResponse>();
        boolean retry = true; 
        int tryCount = 0; 
        while (retry && tryCount <= EsiUtilityAssets.TRY_LIMIT) {
			try {
				tryCount++; 
				response = assetApi.postCharactersCharacterIdAssetsNames(characterId, ids, DATASOURCE, refreshToken); 
		        retry = false; 
			} catch (ApiException e1) {
				e1.printStackTrace();
			}
        }

```
The assetApi is functional, because immediately before I can read the assets through the same api object using getCharactersCharacterIdAssets. Therefore also the characterId and the refreshToken must be correct. 
The ids are extracted from the result of the call to getCharactersCharacterIdAssets. :
```
                List<Long> assetLocations = new ArrayList<Long>();
		for (CharacterAssetsResponse r : assetList) {
			if (!assetLocations.contains(r.getLocationId()) && r.getLocationTypeString().equals("item")) {
				assetLocations.add(r.getLocationId()); 
			}
		}

```

Are there any restrictions on the id´s that may be used here which I am overlooking?

**Comment by GoldenGnu** [comment]
Not all assets item_id's are valid to use with the assets names endpoint.
So, in short only assets that can have names in-game are valid to request with the asset names endpoint.
Here is the ESI issue:
https://github.com/esi/esi-issues/issues/573
Here is the code I use in jEveAssets (it works 100% but it may not include everything):
https://github.com/GoldenGnu/jeveassets/blob/master/src/main/java/net/nikr/eve/jeveasset/io/shared/AbstractGetter.java#L319

I'm going to close this issue, but, feel free to continue commenting if you need additional help getting to work.

**Comment by JoshuaKeno65** [comment]
Thanks for your answer, though I still haven´t figured out completely how to correctly read all the location names for a character´s assets. But I found a workaround that solves my current issue, so I could do what I wanted to do for now.
