### ISSUE TITLE
Unify scope handling

### ISSUE THREAD

**Issue by burberius** [burberius/eve-esi#14]
Currently the scopes are used in three ways: String[], Set<String>, and just a String
That should be unified to only one, preferable Set<String> so checking the supported ones as expected by #13 is easy.

**Comment by GoldenGnu** [comment]
Affected classes/methods are:
eve-esi/src/main/java/net/troja/eve/esi/auth/CharacterInfo.java -> getScopes()
eve-esi/src/main/java/net/troja/eve/esi/auth/SsoScopes.java
eve-esi/src/main/java/net/troja/eve/esi/auth/OAuth.java -> getAuthorizationUri()

**Comment by GoldenGnu** [comment]
Completed with PR #49
