### ISSUE TITLE
Support pagination

### ISSUE THREAD

**Issue by Claudweb** [burberius/eve-esi#32]
Currently the api does not support pagination in a usefull way. The `MarketApi.getMarketsRegionIdOrders` does take a `page` parameter, but there is no way to determine from the result how many pages there are. The result is just a `List<MarketOrderResponse>` but there is no way to get the `"X-Pages"` header to understand how many pages there are.

Either include the pagination logic in the API or make the header available in the response. The first solution would be preferred of course.

**Comment by burberius** [comment]
This could be problematic as the code is generated with Swagger.
We have to look if it's a general way to store it in the header and then change Swagger Codegen or create a patch that is applied after the code generation, what is quite ugly.

**Comment by GoldenGnu** [comment]
It's already possible with `ApiClient.getResponseHeaders()`

**Comment by deadlybulb** [comment]
The swagger spec includes the headers , e.g. here's the header for market/orders:

```
headers: {
Cache-Control: {
description: "The caching mechanism used",
type: "string"
},
Expires: {
description: "RFC7231 formatted datetime string",
type: "string"
},
Last-Modified: {
description: "RFC7231 formatted datetime string",
type: "string"
},
X-Pages: {
default: 1,
description: "Maximum page number",
format: "int32",
type: "integer"
}
```

so a slightly better client generator could add API calls attached to the returned object.  

If I get some time, I'll poke around with the Java code generator a bit.  Last time I looked at the implementation, they assume a very simple HTTP client implementation and don't try to be very fancy.

**Comment by GoldenGnu** [comment]
I'm going to write an example x-pages example. It's pretty simply to do, when you know how it works.

Most people will most likely also need to get the `Expires` header to know when the cache expires and new data is available.

**Comment by GoldenGnu** [comment]
PR with X-pages example ready for review: #33
