### ISSUE TITLE
Update SsoScopes

### ISSUE THREAD

**Issue by Claudweb** [burberius/eve-esi#5]
There are 3 scopes in SsoScopes.java that do not exist anymore:

- esi-mail.organize_mail.v1
- esi-mail.read_mail.v1
- esi-mail.send_mail.v1

**Comment by burberius** [comment]
The Scopes are generated from the swagger.json by my script.
I have to update the code, I hope I'll find time to update soon!

**Comment by Claudweb** [comment]
That is interesting because they still exist in the latest json but I can't find them in https://developers.eveonline.com

**Comment by burberius** [comment]
Looks like a bug on the CCP side, so I will close it.
