### ISSUE TITLE
Error when concatenating scopes

### ISSUE THREAD

**Issue by Claudweb** [burberius/eve-esi#6]
When trying to create a new refresh token containing multiple scopes this fails with "unknown scope". The problem seems to be that the seperating space added in OAuth.getScopesString() is encoded to a '+' in glassfish. I would suggest to just use"%20" instead of ' ' as seperator in OAuth.getScopesString().

**Comment by burberius** [comment]
Does the SsoAuthTest work?
I guess the problem is not the encoding in the URL but #5

**Comment by burberius** [comment]
SsoAuthTest uses only one scope, but it should use all!
I will check that.

**Comment by burberius** [comment]
According to https://tools.ietf.org/html/rfc6749#section-3.3 it must be space separated.
And it works for me that way, but...

Your problem is that there are 2 more scopes that are not public, the fleet one... :-(

**Comment by Claudweb** [comment]
If I concatenate them using %20 it works as expected. When using a space as seperate the displayed url contains a + sign instead of the space for me. The space should be converted to %20 when encoding it to a url.

**Comment by Claudweb** [comment]
But not for CCP

**Comment by burberius** [comment]
The authentication part works for you, too, with the + encoded URL?

**Comment by Claudweb** [comment]
No it only worked if I replaced the + with a %20.

**Comment by burberius** [comment]
https://login.eveonline.com/oauth/authorize?scope=esi-assets.read_assets.v1+esi-skills.read_skills.v1+esi-calendar.respond_calendar_events.v1+esi-corporations.read_corporation_membership.v1+esi-killmails.read_killmails.v1+esi-location.read_ship_type.v1+esi-skills.read_skillqueue.v1+esi-search.search_structures.v1+esi-universe.read_structures.v1+esi-bookmarks.read_character_bookmarks.v1+esi-characters.read_contacts.v1+esi-location.read_location.v1+esi-calendar.read_calendar_events.v1+esi-planets.manage_planets.v1+esi-wallet.read_character_wallet.v1+esi-clones.read_clones.v1&response_type=code&state=somesecret&redirect_uri=http%3A%2F%2Flocalhost&client_id=3569e13affe8844da7958c11779603a0bd

This URL worked for me, when I add all esi-scopes to the applications allowed scopes.

**Comment by Claudweb** [comment]
If I click that link it returns 

{"error":"invalid_client","error_description":"Unknown client"}

**Comment by burberius** [comment]
I changed the client ID. Have a look in Tweetfleet, I sent it to you, there.

**Comment by burberius** [comment]
Information of Claudweb: It is working now. I tried exactly that yesterday with just 2 scopes and it failed. Anyway, it is working now as expected
