### ISSUE TITLE
SsoAuthTest login returns error

### ISSUE THREAD

**Issue by throwfil** [burberius/eve-esi#60]
I tried to run SsoAuthTest, but ran into an issue pretty fast. The esi auth page returns 
`{"error":"invalid_request","error_description":"Some parameters are either missing or invalid"}`
after I logged in with my eve account.

Console output:
```
Authorization URL: https://login.eveonline.com/oauth/authorize?scope=esi-characters.write_contacts.v1+esi-skills.read_skills.v1+esi-characters.read_fatigue.v1+esi-corporations.read_divisions.v1+esi-corporations.read_corporation_membership.v1+esi-bookmarks.read_character_bookmarks.v1+esi-assets.read_corporation_assets.v1+esi-fittings.read_fittings.v1+esi-contracts.read_corporation_contracts.v1+esi-fleets.write_fleet.v1+esi-ui.write_waypoint.v1+esi-industry.read_character_jobs.v1+esi-bookmarks.read_corporation_bookmarks.v1+esi-clones.read_clones.v1+esi-industry.read_character_mining.v1+esi-calendar.respond_calendar_events.v1+esi-characters.read_agents_research.v1+esi-location.read_online.v1+esi-mail.read_mail.v1+esi-characterstats.read.v1+esi-search.search_structures.v1+esi-corporations.read_contacts.v1+esi-corporations.read_container_logs.v1+esi-characters.read_contacts.v1+esi-fittings.write_fittings.v1+esi-markets.structure_markets.v1+esi-wallet.read_corporation_wallets.v1+esi-characters.read_corporation_roles.v1+esi-wallet.read_character_wallet.v1+esi-assets.read_assets.v1+esi-killmails.read_killmails.v1+esi-characters.read_medals.v1+esi-location.read_ship_type.v1+esi-skills.read_skillqueue.v1+esi-contracts.read_character_contracts.v1+esi-mail.send_mail.v1+esi-alliances.read_contacts.v1+esi-location.read_location.v1+esi-ui.open_window.v1+esi-fleets.read_fleet.v1+esi-industry.read_corporation_mining.v1+esi-corporations.read_blueprints.v1+esi-calendar.read_calendar_events.v1+esi-markets.read_character_orders.v1+esi-markets.read_corporation_orders.v1+esi-characters.read_notifications.v1+esi-characters.read_standings.v1+esi-characters.read_opportunities.v1+esi-corporations.read_standings.v1+esi-characters.read_chat_channels.v1+esi-industry.read_corporation_jobs.v1+esi-characters.read_fw_stats.v1+esi-corporations.read_titles.v1+esi-universe.read_structures.v1+esi-corporations.track_members.v1+esi-corporations.read_fw_stats.v1+esi-characters.read_loyalty.v1+esi-mail.organize_mail.v1+esi-corporations.read_structures.v1+esi-corporations.read_outposts.v1+esi-corporations.read_starbases.v1+esi-clones.read_implants.v1+esi-killmails.read_corporation_killmails.v1+esi-corporations.read_medals.v1+esi-planets.manage_planets.v1+esi-characters.read_titles.v1+esi-corporations.read_facilities.v1+esi-characters.read_blueprints.v1+esi-planets.read_customs_offices.v1&response_type=code&state=somesecret&redirect_uri=http%3A%2F%2Flocalhost&client_id=MYCLIENTID
Code from Answer: 
```

Not sure what I'm doing wrong here. I created an application on developers.eveonline.com and added the client id and secret key to the run parameters.

version is 2.1.5

**Comment by GoldenGnu** [comment]
Looks like client secret is missing from the request, I'm not quite sure why...

the run parameters should be (the order is important):
`ClientId ClientSecret`

Alternatively you can set the environment variables:
`SSO_CLIENT_ID` and `SSO_CLIENT_SECRET`
You can also set the `SSO_CALLBACK_URL` environment variables, if you're not using `http://localhost` as your callback url.

You should also note, that if you run the example unmodified, you need to add all scopes to you dev app, for it to work. It's meant as an example, but, it does require you modify the code to fit your needs.

**Comment by throwfil** [comment]
Parameter order is fine, I set the environment variables now as well. The callback url is the same as well. Still the same issue.

I enabled all scopes for test purposes in my application.
I started some debugging, maybe I'll find the problem

**Comment by GoldenGnu** [comment]
`somesecret` is the value used for the `state` in the example.

From our readme:
> Note: The state should be some secret to prevent XRSF, please read: http://www.thread-safe.com/2014/05/the-correct-use-of-state-parameter-in.html

**Comment by GoldenGnu** [comment]
You may have hit one of the SSO issue with max url length.
All browsers, as well as CCPs internal server have a maximum length the url can be.
The limit vary from browser to browser and I can't remember the max for CCPs server.
To be on the safe side, ensure a max url length of 2000 or bellow, that will work with all browsers and servers.

**Comment by throwfil** [comment]
Good to know!

`ALL_VALUES` has a length of ~2300 characters

**Comment by GoldenGnu** [comment]
Good thing we finally figured it out...
I have added an issue to make the example to run by default:
https://github.com/burberius/eve-esi/issues/61
