### ISSUE TITLE
Update SSO example to run by default

### ISSUE THREAD

**Issue by GoldenGnu** [burberius/eve-esi#61]
Using the ALL scope in the SSO example won't work with all browser, due to the URL being too long.
Update the example to use only a few scopes.

**Comment by throwfil** [comment]
Which Browsers work with that long of an URL anyway? 

I tested it with the latest Chrome and Firefox, both failed.

**Comment by GoldenGnu** [comment]
I actually though Chrome would work with 4000 or there about, FireFox used to be capped at 2000 something, but, I don't have any up-to-date info, as all I can find on google is dated by years.
Also, It may be the internal CCPs servers maximum you're hitting and not your browsers.

**Comment by burberius** [comment]
CCP should change the scope strings to be shorter, so everything fits into the URL!

**Comment by GoldenGnu** [comment]
I'm not able to reproduce this.
A lot of changes have been made since the bug report was made (like moving to v2 of SSO).
Maybe, it isn't a problem anymore?

**Comment by burberius** [comment]
Then lets close it and it can be reopened if needed.
