### ISSUE TITLE
How to access the headers from a response

### ISSUE THREAD

**Issue by throwfil** [burberius/eve-esi#62]
for example 
[https://esi.evetech.net/ui/#/Assets/get_characters_character_id_assets](url)
has a header `X-Pages` which contains the count of asset pages. How can I access the headers to get this information?

Sorry, I'm not very familiar with these webstructures.

**Comment by GoldenGnu** [comment]
You can get all headers with
`ApiClient.getResponseHeaders()`

We have helper methods for `expire` and `x-pages`
From the readme:
> If you wonder how the paging with esi works, please have a look at the test
*[src/test/java/net/troja/eve/esi/api/MarketApiTest.java](https://github.com/burberius/eve-esi/blob/master/src/test/java/net/troja/eve/esi/api/MarketApiTest.java#L49)* there is a method *pagingExample* showing it.

**Comment by throwfil** [comment]
Thank you!
