### ISSUE TITLE
Update link to SSO documentation for JWT Token validation

### ISSUE THREAD

**Issue by GoldenGnu** [burberius/eve-esi#68]
Change the SSO documentation links from github to readthedocs

readthedocs is currently not up-to-date, once it's updated the links should be changed

readthedocs:
https://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/index.html
source:
https://github.com/burberius/eve-esi/blob/master/src/main/java/net/troja/eve/esi/auth/JWT.java#L13
https://github.com/burberius/eve-esi/blob/master/src/main/java/net/troja/eve/esi/auth/OAuth.java#L89

**Comment by burberius** [comment]
That documentation is deprecated:
https://eveonline-third-party-documentation.readthedocs.io/en/latest/index.html

Link to https://github.com/esi/esi-docs/blob/master/docs/sso/validating_eve_jwt.md
