### ISSUE TITLE
Stuck at the Beginning

### ISSUE THREAD

**Issue by Synergy0** [burberius/eve-esi#96]
It looks like I'm having a little bit of trouble getting everything started.  This is what I've done so far:  
- everything listed in the setup section of the read me file
- imported the pom.xml file into IntelliJ
- changed the SSO_CLIENT_ID in the GeneralAPITest.java class to the one I generated from the eve developer's website
- changed String state in the main method of the SSOAuthTest.Java class to the secret I generated from the eve developer's website
- ran that main method

The program exit's immediately and says, "ClientId missing"

Can anyone tell me what I'm doing wrong?

Thanks

**Comment by GoldenGnu** [comment]
So, all the things you have done, are things only meant to be done, if you can to contribute and develop on the eveesi library.

To use the library, all you have to do is include eveesi in your pom.xml
As explained here: https://github.com/burberius/eve-esi#maven-integration
For an example of using the library without SSO auth see: https://github.com/burberius/eve-esi#paging
To understand the SSO flow see: https://github.com/burberius/eve-esi/blob/master/src/test/java/net/troja/eve/esi/api/auth/SsoAuthTest.java#L182

I hope that helps get started. But, if you get stuck again, just reply here with your questions

**Comment by Synergy0** [comment]
Thanks.  I will check that out.

**Comment by HerrNerdstrom** [comment]
I had the same problem as well for several frustrating weeks. What I finally did, using eclipse, was to download the ZIP file, expand it in an Eclipse friendly directory, and import it into eclipse. From there I just made a java class with a main(), and started calling the API.

**Comment by GoldenGnu** [comment]
Going to close this, as it appear to be resolved.
Please, create a new issue or comment in this one to have it re-open, if you need additional help.
