### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by HerrNerdstrom** [burberius/eve-esi#97]
For the past week or so I have been getting Bad Gateway errors. As far as I know, nothing in my code has changed. I updated to the latest version of the library from GitHub, but no change. My application gets to near the end of its code before receiving this error. Any ideas?

MainTest.main> Getting all sell orders in Jita 4-4...189331 orders
MainTest.main> Pruning Jita orders...153527 orders
MainTest.main> Retrieving market statistics for Delve...50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950 1000 MainTest.main> Exception: net.troja.eve.esi.ApiException: Bad Gateway
net.troja.eve.esi.ApiException: Bad Gateway
	at net.troja.eve.esi.ApiClient.handleResponse(ApiClient.java:1091)
	at net.troja.eve.esi.ApiClient.execute(ApiClient.java:995)
	at net.troja.eve.esi.api.MarketApi.getMarketsRegionIdHistoryWithHttpInfo(MarketApi.java:1352)
	at net.troja.eve.esi.api.MarketApi.getMarketsRegionIdHistory(MarketApi.java:1321)
	at MainTest.main(MainTest.java:200)

**Comment by deadlybulb** [comment]
This happens in the ESI on occasion, there's not much you can do on the client side except be prepared to handle it (e.g. retry).  Some endpoints are more notorious for this than others.  For example, the corporate contracts API regularly has this issue.

On a typical day in EveKit, one of my sync nodes makes about 500K requests across various API endpoints.  About 2000 of those calls result in errors, and about a third of those errors are 502 (bad gateway).  It's just something you have to be prepared to deal with.

**Comment by HerrNerdstrom** [comment]
Is CCP aware of this issue? Seems like something it might want to fix.

**Comment by GoldenGnu** [comment]
Yes, CCP is aware of the problem, but, it's not something they can fix. as it's AWS that send the error, not ESI itself. Sadly AWS does not allow CCP to customize the error message, hence, why it's html.

I will close this issue, as it's not an eve-esi issue, but, rather an ESI issue (but, no need to make a bug report about it).

See the following for more info about ESI:
https://github.com/esi/esi-docs
https://github.com/esi/esi-issues

**Comment by HerrNerdstrom** [comment]
Thanks for the help and quick responses.
