### ISSUE TITLE
getting 420's

### ISSUE THREAD

**Issue by jjYBdx4IL** [burberius/eve-esi#98]
Why is my error limit remain at 0 when I only do a single request?

Jul 03, 2019 6:18:21 PM okhttp3.internal.platform.Platform log
INFORMATION: --> GET https://esi.evetech.net/verify/?datasource=tranquility
Jul 03, 2019 6:18:21 PM okhttp3.internal.platform.Platform log
INFORMATION: Authorization: Bearer eyJhbGci.....
Jul 03, 2019 6:18:21 PM okhttp3.internal.platform.Platform log
INFORMATION: Accept: application/json
Jul 03, 2019 6:18:21 PM okhttp3.internal.platform.Platform log
INFORMATION: User-Agent: eve-esi/slack:@goldengnu
Jul 03, 2019 6:18:21 PM okhttp3.internal.platform.Platform log
INFORMATION: --> END GET
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: <-- 420 status code 420 https://esi.evetech.net/verify/?datasource=tranquility (360ms)
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: Date: Wed, 03 Jul 2019 16:18:22 GMT
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: Content-Type: application/json; charset=utf-8
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: Content-Length: 429
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: Connection: keep-alive
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: Access-Control-Allow-Credentials: true
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: Access-Control-Allow-Headers: Content-Type,Authorization,If-None-Match,X-User-Agent
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: Access-Control-Allow-Methods: OPTIONS,GET,HEAD,OPTIONS
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: Access-Control-Allow-Origin: *
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: Access-Control-Expose-Headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: Access-Control-Max-Age: 600
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: Allow: OPTIONS,GET,HEAD,OPTIONS
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: Content-Language: en-us
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: Strict-Transport-Security: max-age=31536000
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: Vary: Accept-Language
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: X-Esi-Error-Limit-Remain: 0
Jul 03, 2019 6:18:22 PM okhttp3.internal.platform.Platform log
INFORMATION: X-Esi-Error-Limit-Reset: 38

**Comment by GoldenGnu** [comment]
> Why is my error limit remain at 0 when I only do a single request?
This is not an issue with eve-esi , but, rather something you have to read up on in the ESI documentation.
Please, see the ESI documentation: https://github.com/esi/esi-docs/blob/master/docs/FAQ.md#what-is-the-error-limit
